-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 14:45:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hausmann_BDD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hausmann_BDD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hausmann_BDD` DEFAULT CHARACTER SET utf8 ;
USE `hausmann_BDD` ;

-- -----------------------------------------------------
-- Table `hausmann_BDD`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hausmann_BDD`.`Users` ;

CREATE TABLE IF NOT EXISTS `hausmann_BDD`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(20) NULL,
  `Password` VARCHAR(100) NULL,
  `Name` VARCHAR(100) NULL,
  `Firstname` VARCHAR(100) NULL,
  `Email` VARCHAR(254) NULL,
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `idUsers_UNIQUE` (`idUsers` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hausmann_BDD`.`Recipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hausmann_BDD`.`Recipe` ;

CREATE TABLE IF NOT EXISTS `hausmann_BDD`.`Recipe` (
  `idRecette` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL,
  `Description` VARCHAR(2000) NULL,
  `NbPerson` INT NULL,
  `CookingTime` INT NULL,
  `PreparationTime` INT NULL,
  `Difficulty` TINYINT(3) NULL,
  `ImageSRC` VARCHAR(256) NULL,
  `Type` VARCHAR(100) NULL,
  PRIMARY KEY (`idRecette`),
  UNIQUE INDEX `idRecette_UNIQUE` (`idRecette` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hausmann_BDD`.`Users_has_Recette`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hausmann_BDD`.`Users_has_Recette` ;

CREATE TABLE IF NOT EXISTS `hausmann_BDD`.`Users_has_Recette` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Users_idUsers` INT NOT NULL,
  `Recette_idRecette` INT NOT NULL,
  INDEX `fk_Users_has_Recette_Recette1_idx` (`Recette_idRecette` ASC) VISIBLE,
  INDEX `fk_Users_has_Recette_Users_idx` (`Users_idUsers` ASC) VISIBLE,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_Users_has_Recette_Users`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `hausmann_BDD`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Recette_Recette1`
    FOREIGN KEY (`Recette_idRecette`)
    REFERENCES `hausmann_BDD`.`Recipe` (`idRecette`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hausmann_BDD`.`Aliments_copy1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hausmann_BDD`.`Aliments_copy1` ;

CREATE TABLE IF NOT EXISTS `hausmann_BDD`.`Aliments_copy1` (
  `idAliment` INT NOT NULL,
  `Nom_Aliment` VARCHAR(45) NOT NULL,
  `Calories` VARCHAR(45) NULL,
  `Proteines` VARCHAR(45) NULL,
  PRIMARY KEY (`idAliment`, `Nom_Aliment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hausmann_BDD`.`Ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hausmann_BDD`.`Ingredient` ;

CREATE TABLE IF NOT EXISTS `hausmann_BDD`.`Ingredient` (
  `idAliment` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NULL,
  `Proteins` INT NULL,
  `Calories` INT NULL,
  PRIMARY KEY (`idAliment`),
  UNIQUE INDEX `idAliment_UNIQUE` (`idAliment` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hausmann_BDD`.`Ingredients_Recipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hausmann_BDD`.`Ingredients_Recipe` ;

CREATE TABLE IF NOT EXISTS `hausmann_BDD`.`Ingredients_Recipe` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Recette_idRecette` INT NOT NULL,
  `Aliment_idAliment` INT NOT NULL,
  `Quantity` INT NULL,
  INDEX `fk_Recette_has_Aliment_Aliment1_idx` (`Aliment_idAliment` ASC) VISIBLE,
  INDEX `fk_Recette_has_Aliment_Recette1_idx` (`Recette_idRecette` ASC) VISIBLE,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_Recette_has_Aliment_Recette1`
    FOREIGN KEY (`Recette_idRecette`)
    REFERENCES `hausmann_BDD`.`Recipe` (`idRecette`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recette_has_Aliment_Aliment1`
    FOREIGN KEY (`Aliment_idAliment`)
    REFERENCES `hausmann_BDD`.`Ingredient` (`idAliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hausmann_BDD`.`SavedMeals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hausmann_BDD`.`SavedMeals` ;

CREATE TABLE IF NOT EXISTS `hausmann_BDD`.`SavedMeals` (
  `idSavedMeal` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL,
  `TotCalories` INT NULL,
  PRIMARY KEY (`idSavedMeal`),
  UNIQUE INDEX `idSavedMeal_UNIQUE` (`idSavedMeal` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hausmann_BDD`.`SavedMealsByUsers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hausmann_BDD`.`SavedMealsByUsers` ;

CREATE TABLE IF NOT EXISTS `hausmann_BDD`.`SavedMealsByUsers` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Users_idUsers` INT NOT NULL,
  `SavedMeals_idSavedMeal` INT NOT NULL,
  INDEX `fk_Users_has_SavedMeals_SavedMeals1_idx` (`SavedMeals_idSavedMeal` ASC) VISIBLE,
  INDEX `fk_Users_has_SavedMeals_Users1_idx` (`Users_idUsers` ASC) VISIBLE,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_SavedMeals_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `hausmann_BDD`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_SavedMeals_SavedMeals1`
    FOREIGN KEY (`SavedMeals_idSavedMeal`)
    REFERENCES `hausmann_BDD`.`SavedMeals` (`idSavedMeal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hausmann_BDD`.`Ingredients_Saved`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hausmann_BDD`.`Ingredients_Saved` ;

CREATE TABLE IF NOT EXISTS `hausmann_BDD`.`Ingredients_Saved` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `SavedMeals_idSavedMeal` INT NOT NULL,
  `Ingredient_idAliment` INT NOT NULL,
  `Quantity` INT NULL,
  INDEX `fk_SavedMeals_has_Ingredient_Ingredient1_idx` (`Ingredient_idAliment` ASC) VISIBLE,
  INDEX `fk_SavedMeals_has_Ingredient_SavedMeals1_idx` (`SavedMeals_idSavedMeal` ASC) VISIBLE,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_SavedMeals_has_Ingredient_SavedMeals1`
    FOREIGN KEY (`SavedMeals_idSavedMeal`)
    REFERENCES `hausmann_BDD`.`SavedMeals` (`idSavedMeal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SavedMeals_has_Ingredient_Ingredient1`
    FOREIGN KEY (`Ingredient_idAliment`)
    REFERENCES `hausmann_BDD`.`Ingredient` (`idAliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hausmann_BDD`.`Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hausmann_BDD`.`Type` ;

CREATE TABLE IF NOT EXISTS `hausmann_BDD`.`Type` (
  `idType` INT NOT NULL AUTO_INCREMENT,
  `Particularity` VARCHAR(100) NULL,
  PRIMARY KEY (`idType`),
  UNIQUE INDEX `idType_UNIQUE` (`idType` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hausmann_BDD`.`Recipe_Particularity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hausmann_BDD`.`Recipe_Particularity` ;

CREATE TABLE IF NOT EXISTS `hausmann_BDD`.`Recipe_Particularity` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Recette_idRecette` INT NOT NULL,
  `Type_idType` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Recette_has_Type_Type1_idx` (`Type_idType` ASC) VISIBLE,
  INDEX `fk_Recette_has_Type_Recette1_idx` (`Recette_idRecette` ASC) VISIBLE,
  CONSTRAINT `fk_Recette_has_Type_Recette1`
    FOREIGN KEY (`Recette_idRecette`)
    REFERENCES `hausmann_BDD`.`Recipe` (`idRecette`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recette_has_Type_Type1`
    FOREIGN KEY (`Type_idType`)
    REFERENCES `hausmann_BDD`.`Type` (`idType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
